#!/usr/bin/env bash
set -euo pipefail

: "${ARTIFACT_ROOT:?ARTIFACT_ROOT is required}"
: "${TAG:?TAG is required}"
: "${VERSION:?VERSION is required}"
: "${REPOSITORY:?REPOSITORY is required}"
: "${TAP_DIR:?TAP_DIR is required}"

base_url="https://github.com/${REPOSITORY}/releases/download/${TAG}"

sha_for() {
  local target="$1"
  local checksum="${ARTIFACT_ROOT}/lore-${VERSION}-${target}.tar.gz.sha256"
  [[ -f "$checksum" ]] || { echo "missing checksum: $checksum" >&2; exit 1; }
  awk '{print $1; exit}' "$checksum"
}

url_for() {
  echo "${base_url}/lore-${VERSION}-$1.tar.gz"
}

mac_arm="darwin-arm64"
mac_x86="darwin-amd64"
linux_arm="linux-arm64"
linux_x86="linux-amd64"

formula_dir="${TAP_DIR}/Formula"
mkdir -p "$formula_dir"
formula="${formula_dir}/lore.rb"

cat >"$formula" <<EOF
# This file is generated by scripts/publish-homebrew-tap.sh. Do not edit.
class Lore < Formula
  desc "Project-scoped knowledge portal command-line client"
  homepage "https://github.com/${REPOSITORY}"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "$(url_for "$mac_arm")"
      sha256 "$(sha_for "$mac_arm")"
    end
    on_intel do
      url "$(url_for "$mac_x86")"
      sha256 "$(sha_for "$mac_x86")"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for "$linux_arm")"
      sha256 "$(sha_for "$linux_arm")"
    end
    on_intel do
      url "$(url_for "$linux_x86")"
      sha256 "$(sha_for "$linux_x86")"
    end
  end

  def install
    bin.install "lore"
  end

  test do
    assert_match "lore #{version}", shell_output("#{bin}/lore --version")
  end
end
EOF

cd "$TAP_DIR"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add Formula/lore.rb
if git diff --cached --quiet; then
  echo "Formula unchanged; nothing to commit."
  exit 0
fi
git commit -m "lore ${VERSION}"
git push origin HEAD
